name: stac-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - git
  - intake
  - intake-esm
  - jupyterlab
  - netcdf4
  - pandas
  - pip
  - pydantic
  - pystac
  - python=3.9
  - xarray
  - zarr
  - s3fs
  - pip:
      - git+https://github.com/TomAugspurger/xstac
      - git+https://github.com/aulemahal/xarray.git@calendar-utils
      - git+https://github.com/NCAR/ecgtools.git@main
