name: linting

on:
  push:
  pull_request:

jobs:
  linting:
    if: github.repository == 'NCAR/stac-datastore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
